### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ialbaba** [shilewenuw/get_all_tickers#3]
This is the error im running into when I am trying to run the example code.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-9d454682dfb0> in <module>
----> 1 ticker = gt()

TypeError: 'module' object is not callable

Here's my code
////

import pandas as pd
from get_all_tickers import get_tickers as gt
from get_all_tickers.get_tickers import Region
ticker = gt()

Things of notes:
I'm running python via miniconda. This is the first time I work with packages not in the conda library.

**Comment by shilewenuw** [comment]
We need to call get_tickers on gt. So it should be gt.get_tickers() instead
