### ISSUE TITLE
Package produces NameError using sample code: NameError: name 'get_tickers' is not defined

### ISSUE THREAD

**Issue by compusaurusrex** [shilewenuw/get_all_tickers#4]
Hello

I can get the python program file your wrote (get_tickers.py) to run in a Jupyter notebook, but the package does not run.

I installed the package and get similar results using Jupyter notebook and a Python interpreter.

Here is a screen shot and output in text form for review.

I would sincerely appreciate any suggestions you have on how to resolve this issue!

Thanks, sincerely

![get_tickers_NameError_screen_shot](https://user-images.githubusercontent.com/59968627/95661177-4f64b080-0afb-11eb-9b9a-d55bfda08698.jpg)
[get_tickers_error.txt](https://github.com/shilewenuw/get_all_tickers/files/5359504/get_tickers_error.txt)
![get_tickers_working_Jupyter_screen_shot](https://user-images.githubusercontent.com/59968627/95661308-39a3bb00-0afc-11eb-88b7-d6361552b651.jpg)

**Comment by shilewenuw** [comment]
Hi, because of the NASDAQ anti scraping mechanism, this code will have to be run in a .py file.

**Comment by compusaurusrex** [comment]
Thank you.
