### ISSUE TITLE
get_tickers() method not working in production (AWS Lambda, EC2, Digital Ocean etc)

### ISSUE THREAD

**Issue by pythoneast** [shilewenuw/get_all_tickers#6]
I use your library for getting tickers from exchange markets. But unfortunately get_tickers() method works only locally on my PC. In production (AWS Lambda, AWS EC2, Digital Ocean) it doesn't work and just lags. You use requests library in your method, it doesn't get response from nasdaq and keep waiting until timeout. Can you tell me what is the reason? How can I achieve working of the method in production? Thank you in advance

**Comment by holeyness** [comment]
Also having this problem

**Comment by holeyness** [comment]
I'm pretty sure it's an anti scraping issue

**Comment by shilewenuw** [comment]
as @holeyness mentioned, anti-scraping features makes it so that this only works on a PC. Please note that this package is probably best for research and hobby purposes, for production, I'd suggest a higher quality paid service.
