### ISSUE TITLE
get_tickers miss some symbols

### ISSUE THREAD

**Issue by Jerryli1986** [shilewenuw/get_all_tickers#8]
The total tickers is about 6800, not including 'APPL'
Is it possible to cover all the tickers?

**Comment by herrkaefer** [comment]
> The total tickers is about 6800, not including 'APPL'
> Is it possible to cover all the tickers?

I would guess that you were searching 'AAPL'?

**Comment by shilewenuw** [comment]
all tickers are sourced from NASDAQ, which may or may not be a high quality source.
